import { PDFDocument } from "pdf-lib";
import { readFile, writeFile } from "fs/promises";
import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

type License = { state?: string; number?: string; expirationDate?: string };
type Experience = {
  vehicleType?: string;
  startDate?: string;
  endDate?: string;
  approxMileage?: string;
};
type Accident = {
  date?: string;
  description?: string;
  fatalities?: string;
  injuries?: string;
};
type Violation = {
  date?: string;
  violation?: string;
  state?: string;
  commercialVehicle?: boolean;
};
type Employment = {
  employer?: string;
  startDate?: string;
  endDate?: string;
  address?: string;
  supervisor?: string;
  city?: string;
  state?: string;
  zip?: string;
  phone?: string;
  fmcsr?: boolean;
  cfrPart40?: boolean;
  reasonsForLeaving?: string;
};

type FormData = {
  // Part 1
  date?: string;
  firstName?: string;
  middleName?: string;
  lastName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  dateOfBirth?: string;
  homeTelephone?: string;
  cellularTelephone?: string;
  socialSecurityNumber?: string;
  // Previous addresses
  prevAddress1Street?: string;
  prevAddress1City?: string;
  prevAddress1State?: string;
  prevAddress1Zip?: string;
  prevAddress1DatesFrom?: string;
  prevAddress1DatesTo?: string;
  prevAddress2Street?: string;
  prevAddress2City?: string;
  prevAddress2State?: string;
  prevAddress2Zip?: string;
  prevAddress2DatesFrom?: string;
  prevAddress2DatesTo?: string;
  prevAddress3Street?: string;
  prevAddress3City?: string;
  prevAddress3State?: string;
  prevAddress3Zip?: string;
  prevAddress3DatesFrom?: string;
  prevAddress3DatesTo?: string;
  // Part 2
  license1?: License;
  license2?: License;
  license3?: License;
  experience1?: Experience;
  experience2?: Experience;
  experience3?: Experience;
  accident1?: Accident;
  accident2?: Accident;
  accident3?: Accident;
  // Part 3
  violations?: Violation[];
  denied?: "yes" | "no";
  denialExplanation?: string;
  // Part 4
  employments?: Employment[];
  // Part 5
  signature?: string;
  dateSigned?: string;
};

// Email sending function
async function sendEmailWithPDF(pdfPath: string, formData: FormData) {
  try {
    // Create transporter (configure with your email service)
    const transporter = nodemailer.createTransporter({
      host: process.env.EMAIL_HOST || "smtp.gmail.com",
      port: parseInt(process.env.EMAIL_PORT || "587"),
      secure: false, // true for 465, false for other ports
      auth: {
        user: process.env.EMAIL_USER || "your-email@gmail.com",
        pass: process.env.EMAIL_PASS || "your-app-password",
      },
    });

    // Read the generated PDF
    const pdfBuffer = await readFile(pdfPath);

    // Create email content
    const applicantName = `${formData.firstName || ""} ${
      formData.lastName || ""
    }`.trim();
    const subject =
      process.env.EMAIL_SUBJECT?.replace("{applicantName}", applicantName) ||
      `New Driver Application - ${applicantName}`;

    const mailOptions = {
      from: {
        name: process.env.EMAIL_FROM_NAME || "HBT Inc. Driver Applications",
        address: process.env.EMAIL_USER || "your-email@gmail.com",
      },
      to: process.env.EMAIL_TO || "hr@hbtinc.com",
      subject: subject,
      html: `
        <h2>New Driver Application Received</h2>
        <p><strong>Applicant:</strong> ${applicantName}</p>
        <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        <p><strong>Email:</strong> ${
          formData.homeTelephone || "Not provided"
        }</p>
        <p><strong>Phone:</strong> ${
          formData.homeTelephone || "Not provided"
        }</p>
        <p>Please find the completed application attached.</p>
        <hr>
        <p><em>This email was automatically generated by the HBT Inc. Driver Application System.</em></p>
      `,
      attachments: [
        {
          filename: `driver-application-${applicantName.replace(
            /\s+/g,
            "-"
          )}.pdf`,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    };

    // Send email
    const info = await transporter.sendMail(mailOptions);
    console.log("Email sent successfully:", info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error("Error sending email:", error);
    return { success: false, error: error };
  }
}

async function generatePDF(input: string, output: string, formData: FormData) {
  try {
    const pdfDoc = await PDFDocument.load(await readFile(input));

    // Get form field names for debugging
    const fieldNames: string[] = pdfDoc
      .getForm()
      .getFields()
      .map((f) => f.getName());
    console.log("Available PDF form fields:", fieldNames);

    const form = pdfDoc.getForm();

    // Helper setters that won't throw
    const setText = (name: string, value?: string) => {
      if (!value) return;
      try {
        form.getTextField(name).setText(String(value));
      } catch {
        // ignore missing field
      }
    };
    const setFirstText = (names: string[], value?: string) => {
      if (!value) return;
      for (const n of names) {
        try {
          form.getTextField(n).setText(String(value));
          return;
        } catch {
          // try next
        }
      }
    };
    const setCheck = (name: string, value?: boolean) => {
      if (value === undefined) return;
      try {
        const cb = form.getCheckBox(name);
        if (value) cb.check();
        else cb.uncheck();
      } catch {
        // ignore missing field
      }
    };

    // Map form data to PDF fields
    if (formData.firstName) {
      try {
        form.getTextField("first_name").setText(formData.firstName);
      } catch {
        console.log("Field 'first_name' not found");
      }
    }
    if (formData.lastName) {
      try {
        form.getTextField("last_name").setText(formData.lastName);
      } catch {
        console.log("Field 'last_name' not found");
      }
    }
    if (formData.middleName) {
      try {
        form.getTextField("middle_name").setText(formData.middleName);
      } catch {
        console.log("Field 'middle_name' not found");
      }
    }
    if (formData.address) {
      try {
        form.getTextField("applicant_address").setText(formData.address);
      } catch {
        console.log("Field 'address' not found");
      }
    }
    if (formData.city) {
      try {
        form.getTextField("applicant_city").setText(formData.city);
      } catch {
        console.log("Field 'city' not found");
      }
    }
    if (formData.state) {
      try {
        form.getTextField("applicant_state").setText(formData.state);
      } catch {
        console.log("Field 'state' not found");
      }
    }
    if (formData.zip) {
      try {
        form.getTextField("applicant_zip").setText(formData.zip);
      } catch {
        console.log("Field 'zip' not found");
      }
    }
    if (formData.dateOfBirth) {
      try {
        form.getTextField("DOB").setText(formData.dateOfBirth);
      } catch {
        console.log("Field 'date_of_birth' not found");
      }
    }
    if (formData.homeTelephone) {
      try {
        form
          .getTextField("applicant_telephone")
          .setText(formData.homeTelephone);
      } catch {
        console.log("Field 'home_telephone' not found");
      }
    }
    if (formData.cellularTelephone) {
      try {
        form
          .getTextField("applicant_cellular")
          .setText(formData.cellularTelephone);
      } catch {
        console.log("Field 'cellular_telephone' not found");
      }
    }
    if (formData.socialSecurityNumber) {
      try {
        form
          .getTextField("applicant_ssn")
          .setText(formData.socialSecurityNumber);
      } catch {
        console.log("Field 'social_security_number' not found");
      }
    }

    // Additional mappings
    setText("applicant_date", formData.date);

    // Previous addresses 1..3
    [1, 2, 3].forEach((i) => {
      setText(
        `prev_address${i}_street`,
        (formData as Record<string, string | undefined>)[
          `prevAddress${i}Street`
        ]
      );
      setText(
        `prev_address${i}_city`,
        (formData as Record<string, string | undefined>)[`prevAddress${i}City`]
      );
      setText(
        `prev_address${i}_state`,
        (formData as Record<string, string | undefined>)[`prevAddress${i}State`]
      );
      setText(
        `prev_address${i}_zip`,
        (formData as Record<string, string | undefined>)[`prevAddress${i}Zip`]
      );
      setText(
        `prev_address${i}_from`,
        (formData as Record<string, string | undefined>)[
          `prevAddress${i}DatesFrom`
        ]
      );
      setText(
        `prev_address${i}_to`,
        (formData as Record<string, string | undefined>)[
          `prevAddress${i}DatesTo`
        ]
      );
    });

    // Licenses
    const formatDate = (d?: string) => {
      if (!d) return undefined;
      const m = /^([0-9]{4})-([0-9]{2})-([0-9]{2})$/.exec(d);
      if (m) return `${m[2]}/${m[3]}/${m[1]}`;
      return d;
    };
    [1, 2, 3].forEach((i) => {
      const lic = (formData as Record<string, License | undefined>)[
        `license${i}`
      ];
      if (!lic) return;
      const state = lic.state ? lic.state.toUpperCase().slice(0, 2) : undefined;
      const number = lic.number;
      const exp = formatDate(lic.expirationDate);

      // Map to provided PDF field names and a few fallbacks
      setFirstText(
        [`license_${i}_state`, `license${i}_state`, `dl${i}_state`],
        state
      );
      setFirstText(
        [`license_${i}_num`, `license${i}_number`, `dl${i}_number`],
        number
      );
      setFirstText(
        [
          `License_${i}_expire`,
          `license_${i}_expiration`,
          `license${i}_expiration`,
          `dl${i}_exp`,
        ],
        exp
      );
    });

    // Experience
    [1, 2, 3].forEach((i) => {
      const exp = (formData as Record<string, Experience | undefined>)[
        `experience${i}`
      ];
      if (!exp) return;
      // Vehicle type
      setText(`experience${i}_vehicle_type`, exp.vehicleType);
      setText(`experience_vehicle_${i}`, exp.vehicleType);
      // Start date
      setText(`experience${i}_from`, exp.startDate);
      setText(`experiencne_start_date_${i}`, exp.startDate);
      // End date
      setText(`experience${i}_to`, exp.endDate);
      if (i === 1) setText(`Experience_end_date`, exp.endDate);
      setText(`experience_end_date_${i}`, exp.endDate);
      // Mileage
      setText(`experience${i}_mileage`, exp.approxMileage);
      setText(`applicant_mileage_driven_${i}`, exp.approxMileage);
    });

    // Accidents
    [1, 2, 3].forEach((i) => {
      const acc = (formData as Record<string, Accident | undefined>)[
        `accident${i}`
      ];
      if (!acc) return;
      // Our generic field names
      setText(`accident${i}_date`, acc.date);
      setText(`accident${i}_description`, acc.description);
      setText(`accident${i}_fatalities`, acc.fatalities);
      setText(`accident${i}_injuries`, acc.injuries);
      // Provided PDF field names
      setText(`all_accidents_date_${i}`, acc.date);
      setText(`all_accident_description_${i}`, acc.description);
      setText(`all_accident_fatalities_${i}`, acc.fatalities);
      setText(`all_accidents_injuries_${i}`, acc.injuries);
    });

    // Violations (max 8 rendered fields supported)
    if (formData.violations && formData.violations.length) {
      formData.violations.slice(0, 8).forEach((v, idx) => {
        const i = idx + 1;
        // Generic names
        setText(`violation${i}_date`, v.date);
        setText(`violation${i}_violation`, v.violation);
        setText(`violation${i}_state`, v.state);
        setCheck(`violation${i}_cmv`, v.commercialVehicle);
        // Provided PDF field names
        setText(`violations_date_${i}`, v.date);
        setText(`violation_${i}`, v.violation);
        setText(`violations_state_${i}`, v.state);
        setCheck(`violation_com_vehicle_${i}`, v.commercialVehicle);
      });
    }

    // Denied radio or text
    if (formData.denied) {
      setText("denied", formData.denied);
      setCheck("denied_yes", formData.denied === "yes");
      setCheck("denied_no", formData.denied === "no");
      // Provided PDF fields
      setCheck("license_denied_yes", formData.denied === "yes");
    }
    setText("denial_explanation", formData.denialExplanation);
    setText("license_denied_yes_description", formData.denialExplanation);

    // Employment up to 3
    if (Array.isArray(formData.employments)) {
      formData.employments.slice(0, 3).forEach((e, idx) => {
        const i = idx + 1;
        // Generic fallbacks
        setText(`employment${i}_employer`, e.employer);
        setText(`employment${i}_from`, e.startDate);
        setText(`employment${i}_to`, e.endDate);
        setText(`employment${i}_address`, e.address);
        setText(`employment${i}_supervisor`, e.supervisor);
        setText(`employment${i}_city`, e.city);
        setText(`employment${i}_state`, e.state);
        setText(`employment${i}_zip`, e.zip);
        setText(`employment${i}_phone`, e.phone);
        setCheck(`employment${i}_fmcsr`, e.fmcsr);
        setCheck(`employment${i}_cfr_part40`, e.cfrPart40);
        setText(`employment${i}_reasons`, e.reasonsForLeaving);

        // Provided PDF names examples (you mentioned some):
        // prev-employer-name-1
        setText(`prev-employer-name-${i}`, e.employer);
        // prev-employer-address-2 (address example shows -2 in name; we still align by i)
        setText(`prev-employer-address-${i}`, e.address);
        setText(`prev-employer-start-${i}`, e.startDate);
        setText(`prev-employer-end-${i}`, e.endDate);
        setText(`prev-employer-supervisor-${i}`, e.supervisor);
        setText(`prev-employer-telephone-${i}`, e.phone);
        setCheck(`prev-employer-regulations-yes-${i}`, e.fmcsr);
      });
    }

    // Part 5 - Signature and Date
    setText("applicant_signature", formData.signature);
    setText("date_signed", formData.dateSigned);

    // Flatten the form (make it no longer editable)
    form.flatten();

    const pdfBytes = await pdfDoc.save();
    await writeFile(output, pdfBytes);

    console.log("PDF generated successfully with form data");
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw error;
  }
}
export async function POST(request: Request) {
  try {
    const body = await request.json();

    // Generate PDF with form data
    await generatePDF(
      "./public/application_revised.pdf",
      "appFilled.pdf",
      body
    );

    // Send email with the generated PDF
    const emailResult = await sendEmailWithPDF("appFilled.pdf", body);

    if (emailResult.success) {
      return NextResponse.json({
        message: "PDF generated and email sent successfully",
        emailMessageId: emailResult.messageId,
      });
    } else {
      console.error("Email sending failed:", emailResult.error);
      return NextResponse.json({
        message: "PDF generated successfully, but email failed to send",
        warning: "Email delivery failed",
      });
    }
  } catch (error) {
    console.error("Error in PDF generation or email:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF or send email" },
      { status: 500 }
    );
  }
}
